name: example
description: "Example project to showcase Alice."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.4.0
  path_provider:

dev_dependencies:
  build_runner:
  chopper_generator:
  alice:
    path: ../
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true