name: alice_graphql_client
description: "GraphQL link interceptor and network logger for Alice. Inspect, log, and debug GraphQL operations and responses in a native Flutter UI."
documentation: https://jhomlala.github.io/alice/
repository: https://github.com/jhomlala/alice
issue_tracker: https://github.com/jhomlala/alice/issues
homepage: https://github.com/jhomlala/alice
topics:
  - graphql
  - interceptor
  - logger
  - network
  - link
version: 1.1.1

resolution: workspace

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  alice: ^1.9.0
  graphql: ^5.1.0
  gql: ^1.0.0
  gql_link: ^1.0.0
  gql_exec: ^1.0.0
  meta: ^1.10.0

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
