name: alice_graphql_client
description: A GraphQL adapter for Alice HTTP Inspector. This package provides a GraphQL Link to capture and log GraphQL operations, allowing easy debugging within the Alice UI.
documentation: https://jhomlala.github.io/alice/
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - graphql
  - alice
version: 1.0.4

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  alice: ^1.7.0
  graphql: ^5.1.0
  gql: ^1.0.0
  gql_link: ^1.0.0
  gql_exec: ^1.0.0
  meta: ^1.10.0

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
