analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**.g.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
