analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**.g.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - "**.gen.dart"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
