name: alice_objectbox_example
description: "Alice + ObjectBox + HTTP package - Example"
publish_to: 'none'
resolution: workspace
version: 1.0.0+2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  material_ui: ^1.2.0
  flutter:
    sdk: flutter
  alice:
  alice_http:
  alice_objectbox:
  cupertino_icons: ^1.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
