name: alice_dio_example
description: "A project to showcase dio and alice integration."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_dio:
  path_provider:
  path:
  dio: ^5.4.3+1

dev_dependencies:
  flutter_lints: ^4.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_dio:
    path: ../../packages/alice_dio

flutter:
  uses-material-design: true
