name: alice_dio_example
description: "A project to showcase dio and alice integration."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_dio:
  path_provider:
  path:
  dio: ^5.8.0+1

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice
  alice_dio:
    path: ../../packages/alice_dio

flutter:
  uses-material-design: true
