name: alice_example
description: "Example project to showcase Alice."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  alice:

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0

dependency_overrides:
  alice:
    path: ../../packages/alice

flutter:
  uses-material-design: true
