name: alice_graphql_client_example
description: An example application demonstrating the Alice GraphQL adapter.
version: 0.1.0
publish_to: none
homepage: https://github.com/jhomlala/alice
repository: https://github.com/jhomlala/alice
issue_tracker: https://github.com/jhomlala/alice/issues
resolution: workspace

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
    workspace: true
  alice_graphql_client:
    workspace: true
  graphql_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
